-- GENERATED by database/scripts/generate_dev_seed.mjs — do not edit by hand.
-- Sample data for the local Docker stack ONLY. It creates accounts with known passwords:
--   demo@canineconnections.org / demo1234   (adopter)
--   admin@canineconnections.org / admin1234 (super admin)
-- Never run this against a real database.
USE adoption_center;

INSERT INTO users (user_id, email, password_hash, first_name, last_name, phone, address, role, email_verified) VALUES
  (1, 'demo@canineconnections.org', '$2y$12$yDxunIr4RDTMDJGaEr.ZJ.k8xG/565hqLJLUr6.tujZI.WWHghyym', 'Demo', 'Adopter', '(555) 010-2030', '123 Main St, Newark, NJ', 'adopter', 1),
  (2, 'admin@canineconnections.org', '$2y$12$liKf1bnXX41MxyWX2VAqPOzDzz2GibKI1emYfaP/NjTw1G89Yutsu', 'Alex', 'Admin', '', '', 'super_admin', 1);

INSERT INTO shelters (shelter_id, name, city, state, zip, latitude, longitude, phone, email, website, description, external_id, is_active) VALUES
  (1, 'Hudson Valley Humane Society', 'Newark', 'NJ', '07102', 40.7357, -74.1724, '(973) 555-0142', 'adopt@hvhs.org', 'https://example.org', 'A volunteer-run rescue placing dogs from overcrowded shelters into loving homes since 1998.', 'demo-shelter-1', 1),
  (2, 'Jersey Shore Animal Rescue', 'Asbury Park', 'NJ', '07712', 40.2204, -74.0121, '(732) 555-0187', 'hello@jsar.org', 'https://example.org', 'Foster-based rescue specialising in senior dogs and dogs with medical needs.', 'demo-shelter-2', 1),
  (3, 'Brooklyn Paws Collective', 'Brooklyn', 'NY', '11201', 40.6943, -73.9903, '(718) 555-0199', 'team@brooklynpaws.org', 'https://example.org', 'Urban rescue focused on apartment-ready companions and first-time adopters.', 'demo-shelter-3', 1),
  (4, 'Garden State Greyhound & Hound', 'Princeton', 'NJ', '08540', 40.3573, -74.6672, '(609) 555-0133', 'info@gshound.org', 'https://example.org', 'Hounds of every shape — from retired racers to basset buddies.', 'demo-shelter-4', 1),
  (5, 'Philly Second Chance Dogs', 'Philadelphia', 'PA', '19103', 39.9526, -75.1652, '(215) 555-0110', 'adopt@phillysecondchance.org', 'https://example.org', 'Giving bully breeds and big dogs the second chance they deserve.', 'demo-shelter-5', 1),
  (6, 'Catskill Mountain Rescue', 'Kingston', 'NY', '12401', 41.927, -73.9974, '(845) 555-0171', 'rescue@catskillmr.org', 'https://example.org', 'Active, outdoorsy dogs looking for adventure partners.', 'demo-shelter-6', 1);

INSERT INTO dogs (dog_id, shelter_id, name, breed, age_years, size, gender, description, status, energy_level, good_with_kids, good_with_dogs, good_with_cats, apartment_friendly, requires_yard, training_level, ideal_owner_activity, is_vaccinated, is_spayed_neutered, source, external_id, intake_date) VALUES
  (1, 1, 'Biscuit', 'Beagle', 3, 'medium', 'male', 'Biscuit loves long walks, belly rubs and a good nap in the sun. Great on a leash and already knows sit and stay.', 'available', 'high', 1, 1, 0, 1, 0, 'none', 'active', 1, 1, 'manual', 'demo-1', '2026-08-01'),
  (2, 1, 'Luna', 'Labrador Retriever', 2, 'large', 'female', 'Luna is a gentle soul who warms up quickly and would thrive with a family that enjoys quiet evenings together.', 'available', 'high', 1, 1, 1, 0, 1, 'basic', 'active', 1, 1, 'manual', 'demo-2', '2026-08-01'),
  (3, 2, 'Maple', 'Golden Retriever', 5, 'large', 'female', 'Maple has endless energy and a big heart — perfect for an active household that loves hiking and playing fetch.', 'available', 'medium', 1, 1, 1, 0, 1, 'advanced', 'moderate', 1, 1, 'manual', 'demo-3', '2026-08-01'),
  (4, 6, 'Koda', 'Siberian Husky', 4, 'large', 'male', 'Koda is curious, clever and food-motivated, which makes training a joy. Gets along with most other dogs.', 'available', 'high', 1, 1, 0, 0, 1, 'none', 'active', 1, 1, 'manual', 'demo-4', '2026-08-01'),
  (5, 3, 'Pip', 'Cardigan Welsh Corgi', 1, 'small', 'male', 'Pip is a cuddle champion who will follow you from room to room. Crate trained and house trained.', 'available', 'high', 1, 1, 1, 1, 0, 'basic', 'active', 1, 1, 'manual', 'demo-5', '2026-08-01'),
  (6, 3, 'Coco', 'Standard Poodle', 6, 'large', 'female', 'Coco came to us as a stray and has blossomed into a confident, affectionate companion.', 'available', 'medium', 1, 1, 1, 1, 0, 'advanced', 'moderate', 1, 1, 'manual', 'demo-6', '2026-08-01'),
  (7, 3, 'Otis', 'Pug', 7, 'small', 'male', 'Otis loves long walks, belly rubs and a good nap in the sun. Great on a leash and already knows sit and stay.', 'available', 'low', 1, 1, 1, 1, 0, 'none', 'sedentary', 1, 1, 'manual', 'demo-7', '2026-08-01'),
  (8, 2, 'Frankie', 'Dachshund', 2, 'small', 'male', 'Frankie is a gentle soul who warms up quickly and would thrive with a family that enjoys quiet evenings together.', 'available', 'medium', 0, 1, 1, 1, 0, 'basic', 'moderate', 1, 1, 'manual', 'demo-8', '2026-08-01'),
  (9, 5, 'Rocky', 'Boxer', 4, 'large', 'male', 'Rocky has endless energy and a big heart — perfect for an active household that loves hiking and playing fetch.', 'available', 'high', 1, 0, 0, 0, 1, 'advanced', 'active', 1, 1, 'manual', 'demo-9', '2026-08-01'),
  (10, 3, 'Bella', 'Yorkshire Terrier', 8, 'small', 'female', 'Bella is curious, clever and food-motivated, which makes training a joy. Gets along with most other dogs.', 'available', 'low', 0, 1, 1, 1, 0, 'none', 'sedentary', 1, 1, 'manual', 'demo-10', '2026-08-01'),
  (11, 3, 'Miso', 'Shiba Inu', 3, 'medium', 'female', 'Miso is a cuddle champion who will follow you from room to room. Crate trained and house trained.', 'available', 'medium', 0, 0, 0, 1, 0, 'basic', 'moderate', 1, 1, 'manual', 'demo-11', '2026-08-01'),
  (12, 1, 'Gus', 'French Bulldog', 1, 'small', 'male', 'Gus came to us as a stray and has blossomed into a confident, affectionate companion.', 'available', 'medium', 1, 1, 1, 1, 0, 'advanced', 'moderate', 1, 1, 'manual', 'demo-12', '2026-08-01'),
  (13, 6, 'Scout', 'Border Collie', 2, 'medium', 'female', 'Scout loves long walks, belly rubs and a good nap in the sun. Great on a leash and already knows sit and stay.', 'available', 'high', 1, 1, 0, 0, 1, 'none', 'active', 1, 1, 'manual', 'demo-13', '2026-08-01'),
  (14, 2, 'Daisy', 'Chihuahua', 9, 'small', 'female', 'Daisy is a gentle soul who warms up quickly and would thrive with a family that enjoys quiet evenings together.', 'available', 'low', 0, 1, 1, 1, 0, 'basic', 'sedentary', 1, 1, 'manual', 'demo-14', '2026-08-01'),
  (15, 4, 'Atlas', 'Great Dane', 3, 'extra_large', 'male', 'Atlas has endless energy and a big heart — perfect for an active household that loves hiking and playing fetch.', 'available', 'medium', 1, 1, 1, 0, 1, 'advanced', 'moderate', 1, 1, 'manual', 'demo-15', '2026-08-01'),
  (16, 4, 'Winston', 'Basset Hound', 6, 'medium', 'male', 'Winston is curious, clever and food-motivated, which makes training a joy. Gets along with most other dogs.', 'available', 'low', 1, 1, 1, 1, 0, 'none', 'sedentary', 1, 1, 'manual', 'demo-16', '2026-08-01'),
  (17, 2, 'Rosie', 'Cocker Spaniel', 1, 'medium', 'female', 'Rosie is a cuddle champion who will follow you from room to room. Crate trained and house trained.', 'available', 'medium', 1, 1, 1, 1, 0, 'basic', 'moderate', 1, 1, 'manual', 'demo-17', '2026-08-01'),
  (18, 6, 'Ranger', 'German Shorthaired Pointer', 2, 'large', 'male', 'Ranger came to us as a stray and has blossomed into a confident, affectionate companion.', 'available', 'high', 1, 1, 0, 0, 1, 'advanced', 'active', 1, 1, 'manual', 'demo-18', '2026-08-01'),
  (19, 4, 'Hana', 'Akita', 5, 'large', 'female', 'Hana loves long walks, belly rubs and a good nap in the sun. Great on a leash and already knows sit and stay.', 'available', 'medium', 0, 0, 0, 0, 1, 'none', 'moderate', 1, 1, 'manual', 'demo-19', '2026-08-01'),
  (20, 1, 'Milo', 'Mixed Breed', 0, 'medium', 'male', 'Milo is a gentle soul who warms up quickly and would thrive with a family that enjoys quiet evenings together.', 'available', 'high', 1, 1, 1, 1, 0, 'basic', 'active', 1, 0, 'manual', 'demo-20', '2026-08-01'),
  (21, 5, 'Tank', 'Pit Bull Terrier', 3, 'large', 'male', 'Tank has endless energy and a big heart — perfect for an active household that loves hiking and playing fetch.', 'available', 'medium', 1, 1, 0, 0, 1, 'advanced', 'moderate', 1, 1, 'manual', 'demo-21', '2026-08-01'),
  (22, 3, 'Pearl', 'Maltese', 4, 'small', 'female', 'Pearl is curious, clever and food-motivated, which makes training a joy. Gets along with most other dogs.', 'available', 'low', 1, 1, 1, 1, 0, 'none', 'sedentary', 1, 1, 'manual', 'demo-22', '2026-08-01'),
  (23, 6, 'Nova', 'Samoyed', 2, 'large', 'female', 'Nova is a cuddle champion who will follow you from room to room. Crate trained and house trained.', 'available', 'high', 1, 1, 1, 0, 1, 'basic', 'active', 1, 1, 'manual', 'demo-23', '2026-08-01');

INSERT INTO dog_photos (dog_id, photo_url, is_primary) VALUES
  (1, 'https://images.dog.ceo/breeds/beagle/homer.jpg', 1),
  (2, 'https://images.dog.ceo/breeds/labrador/n02099712_5657.jpg', 1),
  (3, 'https://images.dog.ceo/breeds/retriever-golden/n02099601_70.jpg', 1),
  (4, 'https://images.dog.ceo/breeds/husky/n02110185_11626.jpg', 1),
  (5, 'https://images.dog.ceo/breeds/corgi-cardigan/n02113186_2413.jpg', 1),
  (6, 'https://images.dog.ceo/breeds/poodle-standard/n02113799_2325.jpg', 1),
  (7, 'https://images.dog.ceo/breeds/pug/n02110958_11239.jpg', 1),
  (8, 'https://images.dog.ceo/breeds/dachshund/dachshund-123503_640.jpg', 1),
  (9, 'https://images.dog.ceo/breeds/boxer/n02108089_2670.jpg', 1),
  (10, 'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2519.jpg', 1),
  (11, 'https://images.dog.ceo/breeds/shiba/shiba-4.jpg', 1),
  (12, 'https://images.dog.ceo/breeds/bulldog-french/n02108915_160.jpg', 1),
  (13, 'https://images.dog.ceo/breeds/collie-border/n02106166_3850.jpg', 1),
  (14, 'https://images.dog.ceo/breeds/chihuahua/msdaisy.jpg', 1),
  (15, 'https://images.dog.ceo/breeds/dane-great/n02109047_12193.jpg', 1),
  (16, 'https://images.dog.ceo/breeds/hound-basset/n02088238_9635.jpg', 1),
  (17, 'https://images.dog.ceo/breeds/spaniel-cocker/guusje1.jpg', 1),
  (18, 'https://images.dog.ceo/breeds/pointer-german/n02100236_1164.jpg', 1),
  (19, 'https://images.dog.ceo/breeds/akita/512px-akita_inu.jpg', 1),
  (20, 'https://images.dog.ceo/breeds/mix/milka7.jpg', 1),
  (21, 'https://images.dog.ceo/breeds/pitbull/dog-5437227_640.jpg', 1),
  (22, 'https://images.dog.ceo/breeds/maltese/n02085936_3315.jpg', 1),
  (23, 'https://images.dog.ceo/breeds/samoyed/n02111889_4073.jpg', 1);

INSERT INTO quiz_questions (question_id, question_text, category, display_order) VALUES
  (1, 'What best describes your home?', 'home', 1),
  (2, 'How active is your lifestyle?', 'activity', 2),
  (3, 'What size dog are you hoping for?', 'size', 3),
  (4, 'Are there children in your household?', 'household', 4),
  (5, 'Do you have other pets?', 'pets', 5);

INSERT INTO quiz_options (option_id, question_id, option_text, maps_to_attribute, maps_to_value) VALUES
  (1, 1, 'Apartment or condo', 'apartment_friendly', '1'),
  (2, 1, 'House with a yard', 'requires_yard', '1'),
  (3, 1, 'House without a yard', NULL, NULL),
  (4, 2, 'Relaxed — short walks and couch time', 'energy_level', 'low'),
  (5, 2, 'Moderate — daily walks and weekend outings', 'energy_level', 'medium'),
  (6, 2, 'Very active — running, hiking, lots of play', 'energy_level', 'high'),
  (7, 3, 'Small', 'size', 'small'),
  (8, 3, 'Medium', 'size', 'medium'),
  (9, 3, 'Large', 'size', 'large'),
  (10, 4, 'Yes', 'good_with_kids', '1'),
  (11, 4, 'No', NULL, NULL),
  (12, 5, 'Another dog', 'good_with_dogs', '1'),
  (13, 5, 'A cat', 'good_with_cats', '1'),
  (14, 5, 'No other pets', NULL, NULL);

INSERT INTO success_stories (user_id, dog_id, title, story, status, approved_by) VALUES
  (1, 1, 'Luna found her couch', 'We were nervous first-time adopters, but the matching quiz pointed us to a calm senior who fits our apartment perfectly. Six months later she runs the house.', 'approved', 2),
  (1, 2, 'From shelter to trail buddy', 'Ranger had so much energy the shelter struggled to keep up. Now he hikes with me every weekend and sleeps like a log every night.', 'approved', 2),
  (1, 3, 'Our kids'' best friend', 'The application was simple and the shelter answered every question in Messages. Biscuit has been glued to our kids since day one.', 'approved', 2),
  (1, 4, 'Second chances', 'Tank was overlooked for months. He''s the gentlest dog I''ve ever met.', 'pending', NULL);

INSERT INTO adoption_applications (user_id, dog_id, full_name, address, phone, housing_type, has_yard, has_children, reason_for_adopting, status) VALUES
  (1, 3, 'Demo Adopter', '123 Main St, Newark, NJ', '(555) 010-2030', 'house', 1, 1, 'Looking for a family companion.', 'pending');
