// Generates database/sql/dev_seed.sql from the demo data in frontend/src/services/demoBackend.js,
// so the local Docker stack shows the same shelters, dogs and quiz as `npm run demo`.
// Usage: node database/scripts/generate_dev_seed.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const { DEMO_DATA } = await import(pathToFileURL(path.join(here, "../../frontend/src/services/demoBackend.js")));
const { SHELTERS, DOGS, QUESTIONS, STORIES } = DEMO_DATA;

const q = (v) => (v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/\\/g, "\\\\").replace(/'/g, "''")}'`);
const rows = (list) => list.map((r) => `  (${r.map(q).join(", ")})`).join(",\n");

// Local-only accounts (passwords: demo1234 / admin1234). Never load this file in production.
const DEMO_HASH = "$2y$12$yDxunIr4RDTMDJGaEr.ZJ.k8xG/565hqLJLUr6.tujZI.WWHghyym";
const ADMIN_HASH = "$2y$12$liKf1bnXX41MxyWX2VAqPOzDzz2GibKI1emYfaP/NjTw1G89Yutsu";

const sql = `-- GENERATED by database/scripts/generate_dev_seed.mjs — do not edit by hand.
-- Sample data for the local Docker stack ONLY. It creates accounts with known passwords:
--   demo@canineconnections.org / demo1234   (adopter)
--   admin@canineconnections.org / admin1234 (super admin)
-- Never run this against a real database.
USE adoption_center;

INSERT INTO users (user_id, email, password_hash, first_name, last_name, phone, address, role, email_verified) VALUES
${rows([
  [1, "demo@canineconnections.org", DEMO_HASH, "Demo", "Adopter", "(555) 010-2030", "123 Main St, Newark, NJ", "adopter", 1],
  [2, "admin@canineconnections.org", ADMIN_HASH, "Alex", "Admin", "", "", "super_admin", 1],
])};

INSERT INTO shelters (shelter_id, name, city, state, zip, latitude, longitude, phone, email, website, description, external_id, is_active) VALUES
${rows(SHELTERS.map((s) => [s.shelter_id, s.name, s.city, s.state, s.zip, s.latitude, s.longitude, s.phone, s.email, s.website, s.description, `demo-shelter-${s.shelter_id}`, 1]))};

INSERT INTO dogs (dog_id, shelter_id, name, breed, age_years, size, gender, description, status, energy_level, good_with_kids, good_with_dogs, good_with_cats, apartment_friendly, requires_yard, training_level, ideal_owner_activity, is_vaccinated, is_spayed_neutered, source, external_id, intake_date) VALUES
${rows(DOGS.map((d) => [d.dog_id, d.shelter_id, d.name, d.breed, d.age_years, d.size, d.gender, d.description, d.status, d.energy_level, d.good_with_kids, d.good_with_dogs, d.good_with_cats, d.apartment_friendly, d.requires_yard, d.training_level, d.ideal_owner_activity, d.is_vaccinated, d.is_spayed_neutered, "manual", d.external_id, "2026-08-01"]))};

INSERT INTO dog_photos (dog_id, photo_url, is_primary) VALUES
${rows(DOGS.map((d) => [d.dog_id, d.photos, 1]))};

INSERT INTO quiz_questions (question_id, question_text, category, display_order) VALUES
${rows(QUESTIONS.map((x) => [x.question_id, x.question_text, x.category, x.display_order]))};

INSERT INTO quiz_options (option_id, question_id, option_text, maps_to_attribute, maps_to_value) VALUES
${rows(QUESTIONS.flatMap((x) => x.options.map((o) => [o.option_id, o.question_id, o.option_text, o.maps_to_attribute || null, o.maps_to_value || null])))};

INSERT INTO success_stories (user_id, dog_id, title, story, status, approved_by) VALUES
${rows(STORIES.map((s, i) => [1, (i % DOGS.length) + 1, s.title, s.story, s.status, s.status === "approved" ? 2 : null]))};

INSERT INTO adoption_applications (user_id, dog_id, full_name, address, phone, housing_type, has_yard, has_children, reason_for_adopting, status) VALUES
${rows([[1, 3, "Demo Adopter", "123 Main St, Newark, NJ", "(555) 010-2030", "house", 1, 1, "Looking for a family companion.", "pending"]])};
`;

const out = path.join(here, "../sql/dev_seed.sql");
writeFileSync(out, sql);
console.log(`wrote ${out}`);
